### ISSUE TITLE
infografía sistemas numéricos Kevin Mazarello jose Hernandez  

### ISSUE THREAD

**Issue by kevinMazarelloJOSE** [SistemasTecTlaxiaco/infografia-kevinMazarelloJOSE#1]
![Infografía Matematicas discretas](https://github.com/user-attachments/assets/b0e8a2e7-8daf-4058-93b4-0817ee3db01e)

**Comment by irwingsael** [comment]
Redacción y Ortografía: 12/14
Exposición de ideas Centrales: 16/16
Organización de ideas centrales: 14/14
Uso de Imágenes y Colores: 14/14
Presentación Visual: 14/14
Referencias: 0/14 (no contiene referencias) 
Presentación:14/14
Calificación Final: 16/20

**Comment by josealfredo79** [comment]
Falta agregar mas elementos por favor...debe revisar el lider del equipo por favor..Revisado...
